spring:
  datasource:
    url: jdbc:postgresql://localhost/telegrambot
    password: salam123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    host: ec2-54-73-101-105.eu-west-1.compute.amazonaws.com
    port: 7220
    password: pfc82f367cfbba29b46d2d6633c8c8b42e51a91112c64ca5f892b31017772ba9c


telegrambot:
  username: '@MyTourAppBot'
  path: https://tourappspring.herokuapp.com
  token: 1638447550:AAGL3wR5YBy3juayAx7borJc8XTrDDBX8G4
  proxy:
    type: no_proxy
  lang: 'ENG'
  message-source: Replies
  ignore:
    hard:
      - 'ignore!@#$%^&'
    save:
      - '>|'
      - '<|'


