spring:
#  profiles:
#    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB


telegrambot:
  username: '@MyTourAppBot'
  path: https://tourappspring.herokuapp.com/
  token: 1925789901:AAHh8AkOrUwUrTsXOjCbtqWNLbY8eoP2h_E
  proxy:
    type: no_proxy
  lang: 'ENG'
  message-source: Replies
  ignore:
    hard: 'ignore!@#$%^&'
    save:
      - '>|'
      - '<|'
  redis:
    subscription: telegramuserdata
    dictionary: telegramdictionarydata
    offer: telegramofferdata
  offer:
    image:
      extension: '.png'
      root: src/main/resources/images
    time:
      start: '08:00'
      end: '23:59'
    count: 3

