spring:
  datasource:
    url: jdbc:postgresql://localhost/telegrambot
    password: salam123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

telegrambot:
  username: '@MyTourAppBot'
  path: https://58f2a3693a0e.ngrok.io
  token: 1638447550:AAGL3wR5YBy3juayAx7borJc8XTrDDBX8G4
  proxy:
    type: no_proxy
  lang: 'ENG'
  message-source: Replies



