spring:
  datasource:
    url: jdbc:postgresql://localhost/telegrambot
    password: salam123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    host: 'localhost'
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    template:
      exchange: exchange
      subscription: subscription
      offer: offer


telegrambot:
  username: '@MyTourAppBot'
  path: https://8df46260c34f.ngrok.io
  token: 1638447550:AAGL3wR5YBy3juayAx7borJc8XTrDDBX8G4
  proxy:
    type: no_proxy
  lang: 'ENG'
  message-source: Replies
  ignore:
    hard: 'ignore!@#$%^&'
    save:
      - '>|'
      - '<|'
  redis:
    subscription: telegramuserdata
    dictionary: telegramdictionarydata
    offer: telegramofferdata
  offer:
    image:
      extension: '.png'
      root: src/main/resources/images/
    time:
      start: '08:00'
      end: '23:59'

